[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

[dependencies]
priority-queue = "1.2.1"
hashbrown = "0.11.2"
ahash = "0.7.6"
